### ISSUE TITLE
[FormulasForGoogleDocs] Formula that creates an evaluated formula

### ISSUE THREAD

**Issue by Arglanir** [MikaelMayer/MikaelMayer.github.io#2]
If I create the formula `=("=test")`, then I evaluate formulas, the result will be `=test`.
But if I press Evaluate formulas again, this text is evaluated to whatever the variable `test` is.
If I then press "Reveal formulas", only the `=test` formula is shown, not the original.

Note: is there a way to "escape" formulas in order to show them without evaluation?

**Comment by MikaelMayer** [comment]
In the most recent version to come, i cannot reproduce that bug anymore. The way it fixed it is that it adds the formula `=test` to the display block, but since it also had a formula attached to it, the first one evaluates and removes the second one.

There is no way to "escape" formulas, just embed them in a string like you did and write `=("your formula")`
