### ISSUE TITLE
[FormulasForGoogleDocs] Hide variables initialisation

### ISSUE THREAD

**Issue by Arglanir** [MikaelMayer/MikaelMayer.github.io#3]
(It's not a bug but a Feature Request)
When evaluating formulas, the previously declaration `variable = value` are still displayed. 
Maybe when "Evaluating formulas", you can hide the variable declaration, as if you change them it doesn't directly change the impacted text.
Or maybe automatically evaluate formulas when the document is saved or regularly?

**Comment by MikaelMayer** [comment]
what do you mean by "If you change [variable declarations] it does not directly change the impacted text"? normally if you change a variable's value and click on "evaluate formulas", the computed fields will be updated in the text.

Are you suggesting that variable declarations should automatically be hidden when formulas evaluate, and maybe reappear when clicking on "reveal formulas"?
Potential problems:

* If they are effectively removed and stored in the metadata of the doc, when revealing them they might not be reinserted at the correct place
* If they are hidden in space characters in the document, they might be deleted by accident.

Alternatively, I just defined a way to name the value of an inline formula, so that further formulas can refer to that value. The syntax requires a variable name followed by an equal sign, inside a comment after the first opening parenthesis of a formula, like this:

    The hero's name is =(/*hero=*/“Arglanir”). =hero was known to be a great warrior
    The hero's name is Arglanir. Arglanir was known to be a great warrior

It solves the problem of removing variable declarations, but only if they evaluate to string or rich strings. Variables assigned functions should still be defined separatedly, unless someone has a better idea.

**Comment by MikaelMayer** [comment]
I think the best fix for that will be to enable users to define totally hidden formulas in the formula pane.

**Comment by MikaelMayer** [comment]
In the newest version (that requires Google's approval), there is a dedicated textarea to place definitions that should be hidden from the document. This solves the problem alltogether.
